name: Build Folders on Push

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build Folders
        run: |
          for dir in */; do
            echo "Building $dir"
            cd $dir
            npm ci  # Use `npm install` if you want to update dependencies
            npm run build
            cd ..
          done